version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8765:8765"
    volumes:
      - ./server/chat.db:/app/chat.db
      - ./server/master_key.txt:/app/master_key.txt
    networks:
      - chat-network

  client:
    build: ./client
    ports:
      - "8000:80"
    depends_on:
      - server
    networks:
      - chat-network

  redis:
    image: redis:alpine
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge