version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build: ./server
    ports:
      - "8765:8765"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis

volumes:
  redis_data: