services:
  server:
    build: ./server
    ports:
      - "8765:8765"
    volumes:
      - chat-db-volume:/app/chat.db
      - master-key-volume:/app/master_key
    networks:
      - chat-network

  client:
    build: ./client
    ports:
      - "8000:80"
    depends_on:
      - server
    command: sh -c "sleep 5 && nginx -g 'daemon off;'"  # Задержка 5 секунд перед запуском nginx
    networks:
      - chat-network

  redis:
    image: redis:alpine
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  master-key-volume:
  chat-db-volume: