services:
  server:
    build: ./server
    ports:
      - "8765:8765"
    volumes:
      - ./server/chat.db:/app/chat.db
    environment:
      - MASTER_KEY=WuR1qTOru_Fx85tzO1mzWX-3KVoqm9rKW5QotgHu8qw=  # Замените на безопасный ключ
    depends_on:
      - redis
    networks:
      - chat-network

  client:
    build: ./client
    ports:
      - "8000:80"
    depends_on:
      - server
    networks:
      - chat-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-network

volumes:
  redis-data:
    name: redis-data

networks:
  chat-network:
    driver: bridge